### ISSUE TITLE
Tracking issue for Robonomics Parachains on Kusama Launch

### ISSUE THREAD

**Issue by ensrationis** [airalab/robonomics#145]
**Associated tracking issues:**
* Tracking issue for Kusama Parachains Launch [#2902](https://github.com/paritytech/polkadot/issues/2902)

## Phase 1: Deploy Parachain candidate 
- [ ] Finalise Robonomics Parachain runtime
- [ ] Unit tests for all Parachain runtime components
- [ ] Launch fork of the Finalised Shell Relay chain 
- [ ] Open testnet benchmarking of Earth and Mars under the Shell security

## Phase 2: Integrate to Statemint
- [ ] Support Statemint in Robobank pallets
- [ ] Finalise Statemint support in Robonomics  
- [ ] Connect Statemint parachain to our testnet 
- [ ] Teleport XRT from / to Statemint Parachain
- [ ] Launch IoT device via tokens transfers from Statemint Parachain

## Phase 3: Begin auction
- [ ] Determine final parameters of Crowdloan module
- [ ] Crowdloan final rehearsal 
- [ ] Deploy Crowdloan to  Kusama in time 3rd - 6th auctions.

## Phase 4: Establishing in Kusama network
- [ ] Create technical commitet 
- [ ] Create Parachain Conculs board
- [ ] First protocol upgrade 
- [ ] Exodus, part 2
- [ ] Activate staking mechanism 
- [ ] Kill sudo
